spring:
  application:
    name: ssiren
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ssiren}
    username: ${SPRING_DATASOURCE_USERNAME:ssiren}
    password: ${SPRING_DATASOURCE_PASSWORD:ssiren}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true
