POSTGRES_DB=ssiren
POSTGRES_USER=ssiren
POSTGRES_PASSWORD=ssiren

SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ssiren
SPRING_DATASOURCE_USERNAME=ssiren
SPRING_DATASOURCE_PASSWORD=ssiren
SPRING_JPA_HIBERNATE_DDL_AUTO=create

AI_BASE_URL=http://host.docker.internal:8000

REDIS_HOST=localhost
REDIS_PORT=6379

JWT_SECRET=IFvjTO0qeK4SZnp0n0W46V52MX2xRNujric621PzuFQ
JWT_ACCESS_EXPIRY=1800000
JWT_REFRESH_EXPIRY=604800000

FIREBASE_SERVICE_ACCOUNT_PATH=
FIREBASE_SERVICE_ACCOUNT_JSON=